// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi10ITXZ67f3eUsfEF4PegrZVvyUB3sE8',
    appId: '1:284215528665:web:14a669f38b864db10682c8',
    messagingSenderId: '284215528665',
    projectId: 'toko-untag',
    authDomain: 'toko-untag.firebaseapp.com',
    storageBucket: 'toko-untag.firebasestorage.app',
    measurementId: 'G-WMTP2KS081',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuApIh99CZQUa9lzNZTPuttyL4TnHyL_E',
    appId: '1:284215528665:android:54c490ad4181856f0682c8',
    messagingSenderId: '284215528665',
    projectId: 'toko-untag',
    storageBucket: 'toko-untag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAye5SVdY4_EyiNPg2kdfmX5oukCEj9MvE',
    appId: '1:284215528665:ios:3a2e96a20e8273df0682c8',
    messagingSenderId: '284215528665',
    projectId: 'toko-untag',
    storageBucket: 'toko-untag.firebasestorage.app',
    iosBundleId: 'com.example.tokoUntag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAye5SVdY4_EyiNPg2kdfmX5oukCEj9MvE',
    appId: '1:284215528665:ios:3a2e96a20e8273df0682c8',
    messagingSenderId: '284215528665',
    projectId: 'toko-untag',
    storageBucket: 'toko-untag.firebasestorage.app',
    iosBundleId: 'com.example.tokoUntag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi10ITXZ67f3eUsfEF4PegrZVvyUB3sE8',
    appId: '1:284215528665:web:5e9f7795223500190682c8',
    messagingSenderId: '284215528665',
    projectId: 'toko-untag',
    authDomain: 'toko-untag.firebaseapp.com',
    storageBucket: 'toko-untag.firebasestorage.app',
    measurementId: 'G-JXMYEX0Y6Z',
  );
}
